// Generated registry. Reading order is deliberate — see CLAUDE.md §11.4.
import type { PaperMeta } from './types';

export const papers: PaperMeta[] = [
  {
    n: "01",
    slug: "sunrey-master-economic-operating-system",
    category: "Overview",
    date: "September 2026",
    version: "1.0",
    title: "SunRey Master White Paper",
    subtitle: "An Economic Operating System for the Post-AI Economy",
    abstract: "The unifying document. Sets out four domains of personal economic capability and the three flagship consumer experiences, then traces the whole architecture — SunRey Coin, the Human Information Network, the Vault, MoonRey, Access, Grow My Money, the blockchain and the Exchange — as one integrated economic loop rather than a portfolio of products.",
    notEstablished: "production capability. A public architecture and economic design paper; its closing section states the design boundaries and public commitments the project holds itself to.",
    words: 7021,
    minutes: 32,
    sections: 27,
    figures: 7
  },
  {
    n: "02",
    slug: "sunrey-dual-economy",
    category: "Macroeconomic thesis",
    date: "September 2026",
    title: "The Dual Economy",
    subtitle: "Human Value + Autonomous Productive Value",
    abstract: "The economic argument beneath everything else. Examines what happens when production and labor separate, why the human and autonomous layers must stay distinct rather than collapsing into one asset, and how demand and supply loop between them — through scarcity, participation, systemic risk and a stated research agenda of falsifiable questions.",
    notEstablished: "empirical forecast. In its own words — “not an empirical forecast, monetary-policy recommendation, token offering, securities disclosure, or claim of legally enforceable asset backing.”",
    words: 7615,
    minutes: 35,
    sections: 30,
    figures: 4
  },
  {
    n: "03",
    slug: "sunrey-blockchain-state-machine",
    category: "Protocol architecture",
    date: "September 2026",
    version: "1.0",
    title: "SunRey Blockchain",
    subtitle: "The Sovereign Economic State Machine",
    abstract: "The protocol, in full: identity and actor primitives, rights and consent as native objects, the rich transaction envelope, consensus and finality, the four market families of the Exchange, permission-aware matching, compute-to-data settlement, and evidence treated as an economic primitive rather than a log.",
    notEstablished: "settled parameters. A public technical architecture paper that closes on open architecture decisions and a protocol maturity path, not a specification frozen for implementation.",
    words: 6319,
    minutes: 29,
    sections: 31,
    figures: 10
  },
  {
    n: "04",
    slug: "sunrey-currency-of-you-hin",
    category: "Human economic layer",
    date: "September 2026",
    title: "The Currency of You",
    subtitle: "SunRey Coin and the Human Information Network",
    abstract: "How a person’s information becomes economic participation without becoming property. Traces the path from permission through verified contribution to authorized economic use and compensation, covering compute-to-data, contribution valuation, privacy, and the boundary between human economic value and monetary authority.",
    notEstablished: "monetary parameters. “Public architecture paper. Conceptual design; regulated capabilities and production monetary parameters remain subject to legal, security, governance, and jurisdiction-specific approval.”",
    words: 6215,
    minutes: 28,
    sections: 30,
    figures: 0
  },
  {
    n: "05",
    slug: "moonrey-autonomous-productive-economy",
    category: "Autonomous productive layer",
    date: "September 2026",
    title: "MoonRey",
    subtitle: "The Autonomous Productive Economy",
    abstract: "Productive capacity as an economic object. Builds the Global Productive Capacity Graph, the productive-value pipeline, the oracle mesh and its source-independence rules, then machine economic identity, machine-to-machine commerce and capacity-market instruments — asking what output systems can reliably provide, not what assets exist.",
    notEstablished: "asset backing. “Not a token offering, securities disclosure, investment recommendation, reserve statement or claim of legal asset backing.”",
    words: 6634,
    minutes: 30,
    sections: 32,
    figures: 0
  },
  {
    n: "06",
    slug: "sunrey-access-productive-capacity",
    category: "Economic access",
    date: "September 2026",
    title: "SunRey Access",
    subtitle: "Governed Access to Productive Capacity",
    abstract: "The bridge between participation and real-world capability. Argues the shift from ownership to governed economic access in an automated economy, and specifies an entitlement bounded four ways at once — by rights, by verified capacity, by policy and by solvency — with token state, entitlement state and fiat settlement kept separate.",
    notEstablished: "commercial terms. The paper states it “intentionally omits production allocation coefficients, internal funding assumptions and provider-specific commercial implementation details.”",
    words: 6046,
    minutes: 27,
    sections: 38,
    figures: 6
  },
  {
    n: "07",
    slug: "grow-my-money-ai-financial-agents",
    category: "AI financial systems",
    date: "September 2026",
    title: "Grow My Money",
    subtitle: "An Architecture for Deterministically Authorized AI Financial Agents",
    abstract: "Why AI financial advice is the wrong frame, and what replaces it. Moves from recommendation to bounded agency through permission-aware context, explainable opportunity discovery, deterministic risk limits, policy-gated execution and auditable evidence — making the question one of authority rather than intelligence.",
    notEstablished: "authorization. “Regulated capabilities require jurisdiction-specific licensing, service-provider coverage, legal review, model validation, security approval, and production activation. No investment return is guaranteed.”",
    words: 4873,
    minutes: 22,
    sections: 37,
    figures: 0
  },
  {
    n: "08",
    slug: "proof-of-permission",
    category: "Compliance architecture",
    date: "September 2026",
    title: "Proof of Permission",
    subtitle: "A Compliance-Native Architecture for AI-Driven Financial Systems",
    abstract: "The control doctrine as engineering. Separates intelligence, recommendation and execution authority, then specifies deterministic authorization, machine-readable legal capability, bounded execution authority, canonical ledger truth and reconstructable evidence — so AI can reason and propose without becoming the legal or monetary principal.",
    notEstablished: "legal permission. “This paper describes a technical control model; it does not itself establish legal permission, licensing, regulatory approval, or production authorization in any jurisdiction.”",
    words: 7212,
    minutes: 33,
    sections: 37,
    figures: 5
  },
  {
    n: "09",
    slug: "economic-awareness-sovereign-monetary",
    category: "Monetary architecture",
    date: "September 2026",
    title: "Economic Awareness & Sovereign Monetary Architecture",
    subtitle: "A TIA / Genisys-Inspired Architecture for the Human Economy, the Productive Economy and Proof-Bound Monetary State",
    abstract: "Separating the ability to understand economic reality from the authority to change monetary state. Specifies the Economic Awareness Fabric, source lineage and corroboration, Information Consensus, canonical claims with anti-double-counting, valuation layers that hold no issuance power, and the evidence-to-money firewall.",
    notEstablished: "novelty or approval. “Conceptual design; regulated capabilities, production monetary parameters and claims of technical novelty remain subject to legal, security, governance and jurisdiction-specific review.”",
    words: 5700,
    minutes: 26,
    sections: 25,
    figures: 7
  },
  {
    n: "10",
    slug: "sunrey-post-quantum-security",
    category: "Security architecture",
    date: "September 2026",
    version: "1.0",
    title: "SunRey Post-Quantum Security Architecture",
    subtitle: "A Crypto-Agile, Zero-Trust Security Architecture for Financial Infrastructure, Blockchain and the AI Economy",
    abstract: "A crypto-agile, zero-trust security architecture built on a single premise: that no key, model, service, node, provider, database, employee or connection becomes unrestricted economic authority. Cryptography protects communication and state; deterministic authorization protects economic authority; evidence proves what occurred.",
    notEstablished: "certification. The paper sets an explicit claim discipline and publication boundary, and makes no assertion of completed external audit or attestation.",
    words: 6591,
    minutes: 30,
    sections: 32,
    figures: 8
  }
];

export type { PaperMeta, PaperBlock } from './types';
